version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:3.6.8
    restart: always
    ports:
      - 27017:27017
