version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    volumes:
      - ./:/usr/src/app:cached
      - /usr/src/app/node_modules # anonymous volume for node_modules only
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
  